version: '3.1'
services:
  nodejs:
    build:
      context: ../
      dockerfile: docker/api_nodejs/Dockerfile
    container_name: api_nodejs
    environment:
      - NODE_ENV=production
    networks:
      - subnet_node
      - subnet_db
  postgres:
    image: postgres
    container_name: postgres_tp
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin01
      POSTGRES_DB: test_tp_devops
      PGDATA: "/data/postgres"
    networks:
      - subnet_db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - "HOSTNAME=api:8080"
    depends_on:
      - nodejs
    networks:
      - subnet_node
    ports:
      - 8080:80
  redis:
    image: "redis:alpine"

networks:
  subnet_node:
  subnet_db:
